train:
  path: /../data/feats_train_norm.json

dev:
  path: /../data/feats_dev_norm.json

test:
  path: /../data/feats_test_norm.json


misclassification:
  path: /../data/misclassification.json
correct_classification:
  path: /../data/correct_classification.json

epoch: 1
batch_size: 2
max_len: 160
learning_rate: 0.000001

path_dict_pos:
  path: /../data/dictPositive.p
path_dict_neg:
  path: /../data/dictNegative.p
path_exp:
  path: /../data/expressive_verbs.txt
path_fear:
  path: /../data/keywords_fear.txt
path_manipulation:
  path: /../data/keywords_manipulation.txt
path_pop:
  path: /../data/keywords_populism.txt
path_scandal:
  path: /../data/keywords_scandal.txt
path_secret:
  path: /../data/keywords_secret.txt
path_arousal:
  path: /../data/list_arousal.csv
