file_path:
  path: /plaintext_dataset/

train:
  path: /../recognition_dataset-labeled/train_test.json

dev:
  path: /../recognition_dataset-labeled/dev_test.json

test:
  path: /../recognition_dataset-challenge/test_test.json