train:
  path: /../data/feats_train_norm.json

dev:
  path: /../data/feats_dev_norm.json

test:
  path: /../data/feats_test_norm.json

<<<<<<< HEAD
misclassification:
  path: /../data/misclassification.json
correct_classification:
  path: /../data/correct_classification.json
=======

>>>>>>> 5937b8681549231a4fefa4a666f2296c5e25e942
epoch: 5
batch_size: 16
max_len: 160
learning_rate: 0.000001

path_dict_pos:
  path: /../data/dictPositive.p
path_dict_neg:
  path: /../data/dictNegative.p
path_exp:
  path: /../data/expressive_verbs.txt
path_fear:
  path: /../data/keywords_fear.txt
path_manipulation:
  path: /../data/keywords_manipulation.txt
path_pop:
  path: /../data/keywords_populism.txt
path_scandal:
  path: /../data/keywords_scandal.txt
path_secret:
  path: /../data/keywords_secret.txt
path_arousal:
  path: /../data/list_arousal.csv
